# Generated by Django 5.2.5 on 2025-08-11 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category_course_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cat_course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='myapp.category'),
            preserve_default=False,
        ),
    ]
