# Generated by Django 5.2.5 on 2025-08-12 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_course_cat_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('experience_years', models.PositiveIntegerField()),
                ('qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('languages', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('available_days', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='tutor_profiles/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.subject')),
                ('tutor', models.ForeignKey(limit_choices_to={'role': 'Tutor'}, on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
            options={
                'unique_together': {('tutor', 'subject')},
            },
        ),
    ]
