# Generated by Django 5.2.5 on 2025-08-12 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_tutorexpertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cat_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='myapp.category'),
        ),
    ]
