# Generated by Django 5.2.5 on 2025-08-13 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_course_cat_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_start_date', models.DateTimeField(blank=True, null=True)),
                ('booking_end_date', models.DateTimeField(blank=True, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('communication_preference', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('video_call', 'Video Call')], max_length=20, null=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('paid', 'paid'), ('not paid', 'not paid')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alltutors', to='myapp.login')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='myapp.login')),
            ],
        ),
    ]
