# Generated by Django 5.2.5 on 2025-08-13 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_tutorbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorbooking',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alltutors', to='myapp.tutorexpertise'),
        ),
    ]
