# Generated by Django 5.2.5 on 2025-08-13 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_tutorbooking_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorbooking',
            name='tutordata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alltutors', to='myapp.tutorexpertise'),
        ),
        migrations.AlterField(
            model_name='tutorbooking',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alltutors', to='myapp.login'),
        ),
    ]
