# Generated by Django 5.2.5 on 2025-08-14 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_tutorbooking_tutordata_alter_tutorbooking_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.IntegerField()),
                ('comment', models.CharField(default='', max_length=300)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='all_students', to='myapp.login')),
                ('tutors', models.ForeignKey(default='', limit_choices_to={'role': 'Tutor'}, on_delete=django.db.models.deletion.CASCADE, related_name='all_tutors', to='myapp.login')),
            ],
        ),
    ]
