# Generated by Django 5.2.5 on 2025-08-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cate_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_image',
            field=models.ImageField(blank=True, null=True, upload_to='subject_images/'),
        ),
    ]
