# Generated by Django 5.2.5 on 2025-08-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_category_cate_image_course_course_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorexpertise',
            name='duration_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Number of hours available per day', max_digits=4, null=True),
        ),
    ]
